using System.Text.Json;
using System.Text.Json.Serialization;

namespace MobiCortex.Sdk.Models

{
    /// <summary>
    /// JSON converter for boolean fields that the backend returns as int (1/0).
    /// </summary>
    public class BoolIntConverter : JsonConverter<bool>
    {
        public override bool Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            // Accepts both boolean and integer on read
            if (reader.TokenType == JsonTokenType.True)
                return true;
            if (reader.TokenType == JsonTokenType.False)
                return false;
            if (reader.TokenType == JsonTokenType.Number)
                return reader.GetInt32() != 0;

            throw new JsonException($"Unexpected token type for boolean: {reader.TokenType}");
        }

        public override void Write(Utf8JsonWriter writer, bool value, JsonSerializerOptions options)
        {
            // Writes as boolean true/false
            writer.WriteBooleanValue(value);
        }
    }

    /// <summary>
    /// JSON converter for nullable boolean fields that the backend returns as int (1/0).
    /// </summary>
    public class BoolIntNullableConverter : JsonConverter<bool?>
    {
        public override bool? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            // Accepts both boolean and integer on read
            if (reader.TokenType == JsonTokenType.True)
                return true;
            if (reader.TokenType == JsonTokenType.False)
                return false;
            if (reader.TokenType == JsonTokenType.Number)
                return reader.GetInt32() != 0;
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            throw new JsonException($"Unexpected token type for boolean: {reader.TokenType}");
        }

        public override void Write(Utf8JsonWriter writer, bool? value, JsonSerializerOptions options)
        {
            // Writes as boolean true/false or null
            if (value.HasValue)
                writer.WriteBooleanValue(value.Value);
            else
                writer.WriteNullValue();
        }
    }

    // =============================================================================
    // =============================================================================
    //  DATA MODELS - MobiCortex Master API
    //
    //  All endpoints use the prefix: /mbcortex/master/api/v1/
    //  Example: https://192.168.0.100:4449/mbcortex/master/api/v1/login
    //
    //  DATA HIERARCHY (MobiCortex Model):
    //  +----------------------------------------------------------+
    //  | Central Registry (central-registry / USER6.MCU)          |
    //  |   +-- Entity (entities / ENTITY6.MCU)                    |
    //  |         +-- Access Media (media / MEDIA6.MCU)            |
    //  +----------------------------------------------------------+
    //
    //  A Central Registry can have multiple Entities (persons, vehicles).
    //  An Entity can have multiple Media (card, biometrics, plate, etc).
    // =============================================================================

    #region Generic Response

    /// <summary>
    /// Generic API response with "ret" field.
    /// Values of ret: 0 = success, 1 = generic error/invalid parameter,
    /// 2 = record not found, 3 = limit reached, 4 = duplicate record.
    /// NOTE: This Message comes from the controller's JSON; ApiResult.Message is generated by the SDK.
    /// </summary>
    public class ApiRetResponse
    {
        /// <summary>Return code: 0 = success, > 0 = error.</summary>
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        /// <summary>Descriptive message from the controller (may be null on success).</summary>
        [JsonPropertyName("message")]
        public string? Message { get; set; }
    }

    /// <summary>
    /// Wrapper for API call results.
    /// </summary>
    public class ApiResult<T>
    {
        /// <summary>true if the HTTP response was 2xx (success).</summary>
        public bool Success { get; set; }

        /// <summary>
        /// Deserialized response data.
        /// Populated when Success=true. For HTTP 409 (Conflict), the SDK also
        /// attempts to deserialize the body, allowing inspection of the existing record.
        /// </summary>
        public T? Data { get; set; }

        /// <summary>
        /// Descriptive error message.
        /// For HTTP failures: "HTTP {code}" (e.g.: "HTTP 409"). For exceptions: exception message.
        /// null when Success=true.
        /// </summary>
        public string? Message { get; set; }

        /// <summary>Raw HTTP response body (JSON). Useful for debugging.</summary>
        public string? RawResponse { get; set; }

        /// <summary>
        /// HTTP status code of the response (e.g.: 200, 409, 401).
        /// null when the error was an exception (no HTTP response).
        /// </summary>
        public int? StatusCode { get; set; }

        /// <summary>
        /// true if the server returned HTTP 409 (Conflict).
        /// For entity creation, indicates that the entity already exists.
        /// </summary>
        public bool IsConflict => StatusCode == 409;
    }

    #endregion

    #region Authentication - POST/PUT/DELETE /login

    /// <summary>
    /// POST /login - Login
    /// Body: { "pass": "password" }
    /// </summary>
    public class LoginRequest
    {
        [JsonPropertyName("pass")]
        public string Password { get; set; } = string.Empty;
    }

    /// <summary>
    /// Login response
    /// { "ret": 0, "session_key": "abc123...", "expires_in": 900 }
    /// </summary>
    public class LoginResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        /// <summary>Session token (64-character hex, SHA256)</summary>
        [JsonPropertyName("session_key")]
        public string? SessionKey { get; set; }

        /// <summary>Expiration time in seconds (default: 900 = 15 min)</summary>
        [JsonPropertyName("expires_in")]
        public int ExpiresIn { get; set; }
    }

    /// <summary>
    /// PUT /login - Change password
    /// </summary>
    public class ChangePasswordRequest
    {
        [JsonPropertyName("pass_atual")]
        public string CurrentPassword { get; set; } = string.Empty;

        [JsonPropertyName("pass_nova")]
        public string NewPassword { get; set; } = string.Empty;

        [JsonPropertyName("pass_nova2")]
        public string NewPasswordConfirm { get; set; } = string.Empty;
    }

    /// <summary>
    /// API token listed by GET /token.
    /// </summary>
    public class ApiTokenInfo
    {
        [JsonPropertyName("token")]
        public string Token { get; set; } = string.Empty;

        [JsonPropertyName("label")]
        public string Label { get; set; } = string.Empty;

        [JsonPropertyName("expires_at")]
        public string ExpiresAt { get; set; } = string.Empty;

        [JsonPropertyName("expired")]
        public int Expired { get; set; }
    }

    /// <summary>
    /// Token listing response.
    /// </summary>
    public class ApiTokenListResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("tokens")]
        public List<ApiTokenInfo> Tokens { get; set; } = new();
    }

    /// <summary>
    /// Body for API token creation.
    /// </summary>
    public class CreateApiTokenRequest
    {
        [JsonPropertyName("label")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Label { get; set; }

        [JsonPropertyName("expires_at")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? ExpiresAt { get; set; }

        [JsonPropertyName("ttl_days")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public int? TtlDays { get; set; }
    }

    /// <summary>
    /// Token creation response.
    /// </summary>
    public class ApiTokenCreateResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("token")]
        public string Token { get; set; } = string.Empty;

        [JsonPropertyName("label")]
        public string Label { get; set; } = string.Empty;

        [JsonPropertyName("expires_at")]
        public string ExpiresAt { get; set; } = string.Empty;
    }

    #endregion

    #region Central Registry - GET/POST/DELETE /central-registry

    /// <summary>
    /// Central registry (e.g., "apartment", "company", "resident").
    /// This is the root node of the hierarchy: Registry -> Entities -> Media
    /// </summary>
    public class CentralRegistry
    {
        /// <summary>
        /// Registry ID. Uses uint because IDs created via web
        /// start at 4294000000 (above Int32.MaxValue).
        /// </summary>
        [JsonPropertyName("id")]
        public uint Id { get; set; }

        [JsonPropertyName("name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Name { get; set; }

        /// <summary>true = enabled, false = disabled</summary>
        [JsonPropertyName("enabled")]
        [JsonConverter(typeof(BoolIntConverter))]
        public bool Enabled { get; set; } = true;

        /// <summary>Registry type (free use by the integrator)</summary>
        [JsonPropertyName("type")]
        public int Type { get; set; }

        /// <summary>Free-form fields for additional data</summary>
        [JsonPropertyName("field1")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Field1 { get; set; }

        [JsonPropertyName("field2")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Field2 { get; set; }

        [JsonPropertyName("field3")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Field3 { get; set; }

        [JsonPropertyName("field4")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Field4 { get; set; }

        [JsonPropertyName("slots1")]
        public int Slots1 { get; set; }

        [JsonPropertyName("slots2")]
        public int Slots2 { get; set; }

        /// <summary>Number of linked persons (read-only)</summary>
        [JsonPropertyName("people_count")]
        public uint PeopleCount { get; set; }

        /// <summary>Number of linked vehicles (read-only)</summary>
        [JsonPropertyName("vehicle_count")]
        public uint VehicleCount { get; set; }

        /// <summary>Match reason returned by cross-search (?search=).</summary>
        [JsonPropertyName("match_source")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? MatchSource { get; set; }

        /// <summary>Exact value that caused the match returned by cross-search.</summary>
        [JsonPropertyName("match_value")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? MatchValue { get; set; }

        [JsonPropertyName("created_at")]
        public uint CreatedAt { get; set; }

        [JsonPropertyName("updated_at")]
        public uint UpdatedAt { get; set; }

        /// <summary>
        /// Legacy local alias for the internal slot composition.
        /// The public contract uses only slots1/slots2.
        /// </summary>
        [JsonIgnore]
        public int Capacity
        {
            get => (Slots2 << 4) | (Slots1 & 0x0F);
            set
            {
                Slots1 = value & 0x0F;
                Slots2 = (value >> 4) & 0x0F;
            }
        }

        // Display helpers - Converts from UTC to Brasilia time (UTC-3)
        [JsonIgnore]
        public string CreatedAtFormatted => CreatedAt > 0
            ? TimeZoneInfo.ConvertTimeBySystemTimeZoneId(
                DateTimeOffset.FromUnixTimeSeconds(CreatedAt).UtcDateTime,
                "E. South America Standard Time").ToString("dd/MM/yyyy HH:mm")
            : "-";

        [JsonIgnore]
        public string UpdatedAtFormatted => UpdatedAt > 0
            ? TimeZoneInfo.ConvertTimeBySystemTimeZoneId(
                DateTimeOffset.FromUnixTimeSeconds(UpdatedAt).UtcDateTime,
                "E. South America Standard Time").ToString("dd/MM/yyyy HH:mm")
            : "-";
    }

    /// <summary>
    /// GET /central-registry?offset=0&amp;count=20&amp;name=filter
    /// Paginated response for registry listing
    /// </summary>
    public class RegistryListResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        /// <summary>Number of items returned in this page</summary>
        [JsonPropertyName("count")]
        public uint Count { get; set; }

        /// <summary>Total records in the controller (for pagination)</summary>
        [JsonPropertyName("total")]
        public uint Total { get; set; }

        [JsonPropertyName("items")]
        public List<CentralRegistry> Items { get; set; } = new();
    }

    /// <summary>
    /// GET /central-registry/stats
    /// Central registry usage statistics
    /// </summary>
    public class RegistryStats
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("max_capacity")]
        public int MaxCapacity { get; set; }

        [JsonPropertyName("current_total")]
        public int CurrentTotal { get; set; }

        [JsonPropertyName("usage_percent")]
        public double UsagePercent { get; set; }
    }

    #endregion

    #region Entities - GET/POST/PUT/DELETE /entities

    /// <summary>
    /// Available entity types
    /// </summary>
    public enum EntityType
    {
        Person = 1,
        Vehicle = 2,
        Animal = 3
    }

    /// <summary>
    /// Entity (person, vehicle, or animal) linked to a Central Registry.
    /// Each entity can have multiple access media.
    /// </summary>
    public class Entity
    {
        [JsonPropertyName("ret")]
        public int? Ret { get; set; }

        [JsonPropertyName("entity_id")]
        public uint EntityId { get; set; }

        [JsonPropertyName("central_registry_id")]
        public uint CentralRegistryId { get; set; }

        /// <summary>1=Person, 2=Vehicle, 3=Animal</summary>
        [JsonPropertyName("type")]
        public int Type { get; set; }

        /// <summary>true = enabled, false = disabled</summary>
        [JsonPropertyName("enabled")]
        [JsonConverter(typeof(BoolIntConverter))]
        public bool Enabled { get; set; } = true;

        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;

        /// <summary>Document (CPF, plate, etc.)</summary>
        [JsonPropertyName("doc")]
        public string Doc { get; set; } = string.Empty;

        /// <summary>Vehicle brand (optional, used when type=2)</summary>
        [JsonPropertyName("brand")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Brand { get; set; }

        /// <summary>Vehicle model (optional, used when type=2)</summary>
        [JsonPropertyName("model")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Model { get; set; }

        /// <summary>Vehicle color (optional, used when type=2)</summary>
        [JsonPropertyName("color")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Color { get; set; }

        /// <summary>Legacy field. The current controller does not expose `obs` in the public entities contract.</summary>
        [Obsolete("The current backend does not use the obs field in entities. Keep only for local compatibility.")]
        [JsonPropertyName("obs")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Obs { get; set; }
        /// <summary>
        /// true = LPR active. When enabled, the controller automatically creates
        /// an LPR-type media using the "doc" field as the plate.
        /// </summary>
        [JsonPropertyName("lpr_enabled")]
        [JsonConverter(typeof(BoolIntConverter))]
        public bool LprEnabled { get; set; }

        [JsonPropertyName("created_at")]
        public uint CreatedAt { get; set; }

        [JsonPropertyName("updated_at")]
        public uint UpdatedAt { get; set; }

        // Helpers
        [JsonIgnore]
        public uint RegistryId
        {
            get => CentralRegistryId;
            set => CentralRegistryId = value;
        }

        [JsonIgnore]
        public int TypeAlias
        {
            get => Type;
            set => Type = value;
        }

        [JsonIgnore]
        public bool LprActive
        {
            get => LprEnabled;
            set => LprEnabled = value;
        }

        [JsonIgnore]
        public string TypeName => (EntityType)Type switch
        {
            EntityType.Person => "Person",
            EntityType.Vehicle => "Vehicle",
            EntityType.Animal => "Animal",
            _ => $"Type {TypeAlias}"
        };

        [JsonIgnore]
        public string DisplayName
        {
            get
            {
                if ((EntityType)Type != EntityType.Vehicle)
                {
                    return Name;
                }

                var parts = new[] { Brand, Model, Color }
                    .Where(value => !string.IsNullOrWhiteSpace(value))
                    .Select(value => value!.Trim());

                var description = string.Join(" / ", parts);
                if (!string.IsNullOrWhiteSpace(description))
                {
                    return description;
                }

                if (!string.IsNullOrWhiteSpace(Doc))
                {
                    return $"Vehicle {Doc}";
                }

                return Name;
            }
        }

        [JsonIgnore]
        public string CreatedAtFormatted => CreatedAt > 0
            ? DateTimeOffset.FromUnixTimeSeconds(CreatedAt).LocalDateTime.ToString("dd/MM/yyyy HH:mm")
            : "-";

        [JsonIgnore]
        public string UpdatedAtFormatted => UpdatedAt > 0
            ? DateTimeOffset.FromUnixTimeSeconds(UpdatedAt).LocalDateTime.ToString("dd/MM/yyyy HH:mm")
            : "-";
    }

    /// <summary>
    /// POST /entities - Create entity.
    /// Use createid=true to generate IDs automatically (simple model).
    /// </summary>
    public class CreateEntityRequest
    {
        /// <summary>
        /// Entity ID.
        /// - 0: controller generates automatically
        /// - &gt;0: uses the provided ID
        /// </summary>
        [JsonPropertyName("id")]
        public uint Id { get; set; }

        /// <summary>
        /// ID of the central registry to link the entity to.
        /// Required in the MobiCortex model. Ignored if createid=true.
        /// </summary>
        [JsonPropertyName("central_registry_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public uint? CentralRegistryId { get; set; }

        /// <summary>1=Person, 2=Vehicle, 3=Animal</summary>
        [JsonPropertyName("type")]
        public int Type { get; set; } = 1;

        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; } = true;

        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;

        /// <summary>Document (CPF, plate, etc.)</summary>
        [JsonPropertyName("doc")]
        public string Doc { get; set; } = string.Empty;

        /// <summary>Vehicle brand (optional)</summary>
        [JsonPropertyName("brand")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Brand { get; set; }

        /// <summary>Vehicle model (optional)</summary>
        [JsonPropertyName("model")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Model { get; set; }

        /// <summary>Vehicle color (optional)</summary>
        [JsonPropertyName("color")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Color { get; set; }

        /// <summary>Legacy field. The current controller's public contract does not use `obs` in entities.</summary>
        [Obsolete("The current backend does not accept the obs field in entities. Keep only for local compatibility.")]
        [JsonIgnore]
        public string? Obs { get; set; }

        /// <summary>true = enable plate recognition via LPR for vehicle</summary>
        [JsonPropertyName("lpr_enabled")]
        public bool LprEnabled { get; set; }

        /// <summary>
        /// true = generates entity_id and central_registry_id automatically.
        /// Used in the simple model (without creating a central registry first).
        /// The controller creates everything internally.
        /// </summary>
        [JsonPropertyName("createid")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? CreateId { get; set; }

        /// <summary>
        /// When true, overwrites the existing entity (handles HTTP 409).
        /// Recommended flow: 1) Create without Overwrite, 2) If result.IsConflict, prompt the user,
        /// 3) If confirmed, resend with Overwrite=true.
        /// Requires Id > 0 (does not work with CreateId=true).
        /// </summary>
        [JsonPropertyName("overwrite")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public bool? Overwrite { get; set; }

        [JsonIgnore]
        public uint? RegistryId
        {
            get => CentralRegistryId;
            set => CentralRegistryId = value;
        }

        [JsonIgnore]
        public int TypeAlias
        {
            get => Type;
            set => Type = value;
        }

        [JsonIgnore]
        public bool LprActive
        {
            get => LprEnabled;
            set => LprEnabled = value;
        }
    }

    /// <summary>
    /// Response from POST /entities.
    /// Success (HTTP 200, ret=0): entity created, EntityId and CentralRegistryId populated.
    /// Conflict (HTTP 409): entity already exists with the provided ID.
    ///   Use Overwrite=true in the request to overwrite, or PUT /entities?id=X to update.
    /// </summary>
    public class CreateEntityResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("entity_id")]
        public uint EntityId { get; set; }

        [JsonPropertyName("central_registry_id")]
        public uint CentralRegistryId { get; set; }

        /// <summary>1 if the central registry was created automatically</summary>
        [JsonPropertyName("created_central")]
        public int CreatedCentral { get; set; }

        /// <summary>1 if an existing entity was overwritten (overwrite)</summary>
        [JsonPropertyName("updated_existing")]
        public int UpdatedExisting { get; set; }

        [JsonIgnore]
        public uint RegistryId
        {
            get => CentralRegistryId;
            set => CentralRegistryId = value;
        }
    }

    /// <summary>
    /// PUT /entities?id=X - Update entity (partial).
    ///
    /// Specific model for updates. Unlike CreateEntityRequest,
    /// this model allows partial updates: populate only the fields you
    /// want to modify. Null fields are ignored during serialization (not sent).
    ///
    /// Example: person uses name/doc; vehicle uses doc/brand/model/color/lpr_enabled.
    /// Null fields are still omitted from the payload.
    /// </summary>
    public class UpdateEntityRequest
    {
        [JsonPropertyName("enabled")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonConverter(typeof(BoolIntNullableConverter))]
        public bool? Enabled { get; set; }

        [JsonPropertyName("name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Name { get; set; }

        [JsonPropertyName("doc")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Doc { get; set; }

        [JsonPropertyName("brand")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Brand { get; set; }

        [JsonPropertyName("model")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Model { get; set; }

        [JsonPropertyName("color")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Color { get; set; }

        /// <summary>Legacy field. The current controller's public contract does not use `obs` in entities.</summary>
        [Obsolete("The current backend does not accept the obs field in entities. Keep only for local compatibility.")]
        [JsonIgnore]
        public string? Obs { get; set; }
        [JsonPropertyName("lpr_enabled")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonConverter(typeof(BoolIntNullableConverter))]
        public bool? LprEnabled { get; set; }

        [JsonIgnore]
        public bool? LprActive
        {
            get => LprEnabled;
            set => LprEnabled = value;
        }
    }

    /// <summary>
    /// GET /entities?central_registry_id=X  -> lists entities of a registry (no pagination)
    /// GET /entities?offset=X&amp;count=Y  -> global paginated list
    /// GET /entities?offset=X&amp;count=Y&amp;name=filter  -> with server-side filter
    /// </summary>
    public class EntityListResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        /// <summary>Total entities in the controller (present in global paginated listing)</summary>
        [JsonPropertyName("total")]
        public uint Total { get; set; }

        [JsonPropertyName("count")]
        public uint Count { get; set; }

        /// <summary>Present only when filtered by central_registry_id</summary>
        [JsonPropertyName("central_registry_id")]
        public uint? CentralRegistryId { get; set; }

        [JsonPropertyName("items")]
        public List<Entity> Items { get; set; } = new();

        [JsonIgnore]
        public uint? RegistryId
        {
            get => CentralRegistryId;
            set => CentralRegistryId = value;
        }
    }

    /// <summary>
    /// GET /vehicle-drivers?vehicle_id=X
    /// </summary>
    public class VehicleDriverListResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("vehicle_id")]
        public uint VehicleId { get; set; }

        [JsonPropertyName("driver_ids")]
        public List<uint> DriverIds { get; set; } = new();
    }

    /// <summary>
    /// PUT /vehicle-drivers?vehicle_id=X
    /// </summary>
    public class UpdateVehicleDriversRequest
    {
        [JsonPropertyName("driver_ids")]
        public List<uint> DriverIds { get; set; } = new();
    }

    /// <summary>
    /// Response for vehicle-driver link update.
    /// </summary>
    public class VehicleDriverUpdateResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("vehicle_id")]
        public uint VehicleId { get; set; }

        [JsonPropertyName("count")]
        public int Count { get; set; }
    }

    /// <summary>
    /// DELETE /entities/cleanup-orphans
    /// Removes central registries with no linked entities.
    /// </summary>
    public class CleanupOrphansResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("scanned")]
        public uint Scanned { get; set; }

        [JsonPropertyName("orphans_deleted")]
        public uint OrphansDeleted { get; set; }
    }

    #endregion

    #region Access Media - GET/POST/PUT/DELETE /media

    /// <summary>
    /// Access media types supported by the controller.
    ///
    /// IMPORTANT ABOUT LPR (PLATE):
    /// - Type 17 = LPR (vehicle plate recognition)
    /// - When creating an LPR media manually via POST /media, you must send
    ///   the ns32_0 and ns32_1 fields to prevent the backend from trying to validate the plate
    ///   as if it were an RFID format (Wiegand/CODE/HEX).
    /// - The RECOMMENDED way to create LPR is to use lpr_enabled=true on the vehicle entity,
    ///   as the backend creates/updates the LPR media automatically.
    /// </summary>
    public static class MediaType
    {
        public const int RemoteControl = 0;    // Remote control HT
        public const int Hcs = 1;              // HCS
        public const int Bio = 5;              // Biometrics
        public const int Keyboard = 8;         // Password/Keyboard
        public const int Bio2 = 12;            // Biometrics 2
        public const int Mc = 14;              // MC Control
        public const int Bio3 = 15;            // Biometrics 3
        public const int Lpr = 17;             // Plate (LPR) - see note above
        public const int BioHikvision = 18;    // Biometrics Hikvision
        public const int BioNiceWego = 19;     // Biometrics Nice Wego
        public const int Facial = 20;          // Facial recognition
        public const int Wiegand26 = 21;       // RFID Card Wiegand 26 bits
        public const int Wiegand34 = 22;       // RFID Card Wiegand 34 bits

        /// <summary>Returns the human-readable name of the media type</summary>
        public static string GetName(int type) => type switch
        {
            RemoteControl => "Remote Control",
            Hcs => "HCS",
            Bio or Bio2 or Bio3 => "Biometrics",
            Keyboard => "Password/Keyboard",
            Mc => "MC Control",
            Lpr => "Plate (LPR)",
            BioHikvision => "Bio Hikvision",
            BioNiceWego => "Bio Nice Wego",
            Facial => "Facial",
            Wiegand26 => "RFID Wiegand 26",
            Wiegand34 => "RFID Wiegand 34",
            _ => $"Type {type}"
        };
    }

    /// <summary>
    /// Access media (card, biometrics, plate, etc.).
    /// Linked to an Entity and a Central Registry.
    /// </summary>
    public class AccessMedia
    {
        [JsonPropertyName("ret")]
        public int? Ret { get; set; }

        [JsonPropertyName("media_id")]
        public uint MediaId { get; set; }

        [JsonPropertyName("entity_id")]
        public uint EntityId { get; set; }

        [JsonPropertyName("central_registry_id")]
        public uint CentralRegistryId { get; set; }

        /// <summary>Media type (see constants in MediaType)</summary>
        [JsonPropertyName("type")]
        public int Type { get; set; }

        [JsonPropertyName("description")]
        public string Description { get; set; } = string.Empty;

        /// <summary>true = enabled, false = disabled</summary>
        [JsonPropertyName("enabled")]
        [JsonConverter(typeof(BoolIntConverter))]
        public bool Enabled { get; set; } = true;

        [JsonPropertyName("created_at")]
        public uint CreatedAt { get; set; }

        [JsonPropertyName("updated_at")]
        public uint UpdatedAt { get; set; }

        /// <summary>Expiration date/time (UNIX timestamp). 0 = no expiration.</summary>
        [JsonPropertyName("expiration")]
        public uint Expiration { get; set; }

        [JsonIgnore]
        public uint DtBlock
        {
            get => Expiration;
            set => Expiration = value;
        }

        [JsonIgnore]
        public uint RegistryId
        {
            get => CentralRegistryId;
            set => CentralRegistryId = value;
        }

        [JsonIgnore]
        public int TypeAlias
        {
            get => Type;
            set => Type = value;
        }

        [JsonIgnore]
        public string DescriptionAlias
        {
            get => Description;
            set => Description = value;
        }

        [JsonIgnore]
        public string TypeName => MediaType.GetName(Type);

        [JsonIgnore]
        public bool HasDateBlock => Expiration > 0 && Expiration > DateTimeOffset.UtcNow.ToUnixTimeSeconds();

        [JsonIgnore]
        public string BlockedUntil => Expiration > 0
            ? DateTimeOffset.FromUnixTimeSeconds(Expiration).LocalDateTime.ToString("dd/MM/yyyy HH:mm")
            : "-";

        [JsonIgnore]
        public string CreatedAtFormatted => CreatedAt > 0
            ? DateTimeOffset.FromUnixTimeSeconds(CreatedAt).LocalDateTime.ToString("dd/MM/yyyy HH:mm")
            : "-";

        [JsonIgnore]
        public string UpdatedAtFormatted => UpdatedAt > 0
            ? DateTimeOffset.FromUnixTimeSeconds(UpdatedAt).LocalDateTime.ToString("dd/MM/yyyy HH:mm")
            : "-";
    }

    /// <summary>
    /// POST /media - Create access media
    ///
    /// HOW TO REGISTER DIFFERENT MEDIA TYPES:
    ///
    /// 1. RFID (Wiegand/CODE/HEX):
    ///    - Send only entity_id, central_registry_id, type and description
    ///    - The backend automatically detects the format (Wiegand 123,45678 / CODE / HEX)
    ///    - Example: description = "123,45678" or "HEX: FF FF FF"
    ///
    /// 2. LPR (Vehicle plate):
    ///    - Send entity_id, central_registry_id, type=17, description="ABC1D23"
    ///    - IMPORTANT: also send ns32_0=0 and ns32_1=0
    ///    - Without ns32_0/ns32_1, the backend tries to validate the plate as RFID and returns an error
    ///    - NOTE: The recommended way is to use lpr_enabled=true on the vehicle entity,
    ///      as the backend creates/updates the LPR media automatically
    ///
    /// 3. Facial, Biometrics, etc.:
    ///    - Send entity_id, central_registry_id, type and description
    ///    - To avoid RFID validation, send ns32_0=0 and ns32_1=0
    /// </summary>
    public class CreateMediaRequest
    {
        [JsonPropertyName("entity_id")]
        public uint EntityId { get; set; }

        [JsonPropertyName("central_registry_id")]
        public uint CentralRegistryId { get; set; }

        /// <summary>Media type (see constants MediaType.*)</summary>
        [JsonPropertyName("type")]
        public int Type { get; set; } = MediaType.Wiegand26;

        /// <summary>
        /// Description/value of the media.
        /// - RFID: card code (e.g.: "123,45678" or "HEX: FF FF FF")
        /// - LPR: vehicle plate (e.g.: "ABC1D23")
        /// - Facial/Other: descriptive identifier
        /// </summary>
        [JsonPropertyName("description")]
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Numeric value NS32_0 - used internally by the backend to store
        /// binary media data (RFID, converted plate, etc.).
        ///
        /// WHEN TO USE:
        /// - RFID: do not send (the backend calculates from the description)
        /// - LPR/Facial/Other: send 0 to avoid RFID validation
        /// </summary>
        [JsonPropertyName("ns32_0")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public uint? Ns32_0 { get; set; }

        /// <summary>
        /// Numeric value NS32_1 - used internally by the backend to store
        /// binary media data (high part of long IDs).
        ///
        /// WHEN TO USE:
        /// - RFID: do not send (the backend calculates from the description)
        /// - LPR/Facial/Other: send 0 to avoid RFID validation
        /// </summary>
        [JsonPropertyName("ns32_1")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public uint? Ns32_1 { get; set; }

        [JsonIgnore]
        public uint RegistryId
        {
            get => CentralRegistryId;
            set => CentralRegistryId = value;
        }

        [JsonIgnore]
        public int TypeAlias
        {
            get => Type;
            set => Type = value;
        }

        [JsonIgnore]
        public string DescriptionAlias
        {
            get => Description;
            set => Description = value;
        }
    }

    /// <summary>
    /// Response from POST /media
    /// </summary>
    public class CreateMediaResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("media_id")]
        public uint MediaId { get; set; }
    }

    /// <summary>
    /// GET /media?entity_id=X - Lists media for an entity
    /// </summary>
    public class MediaListResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("entity_id")]
        public uint EntityId { get; set; }

        [JsonPropertyName("count")]
        public int Count { get; set; }

        [JsonPropertyName("items")]
        public List<AccessMedia> Items { get; set; } = new();
    }

    #endregion

    #region Dashboard and Device

    /// <summary>
    /// Default color item returned by GET /vehicle-catalogs.
    /// </summary>
    public class VehicleColorCatalogItem
    {
        [JsonPropertyName("code")]
        public int Code { get; set; }

        [JsonPropertyName("label")]
        public string Label { get; set; } = string.Empty;
    }

    /// <summary>
    /// Suggested brand item returned by GET /vehicle-catalogs.
    /// </summary>
    public class VehicleBrandCatalogItem
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;
    }

    /// <summary>
    /// GET /vehicle-catalogs - auxiliary catalogs for vehicle registration.
    /// </summary>
    public class VehicleCatalogsResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("colors")]
        public List<VehicleColorCatalogItem> Colors { get; set; } = new();

        [JsonPropertyName("brands")]
        public List<VehicleBrandCatalogItem> Brands { get; set; } = new();

        [JsonPropertyName("colors_count")]
        public int ColorsCount { get; set; }

        [JsonPropertyName("brands_count")]
        public int BrandsCount { get; set; }
    }

    /// <summary>
    /// GET /dashboard - General controller statistics
    /// </summary>
    public class DashboardStats
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("counts")]
        public DashboardCounts Counts { get; set; } = new();

        [JsonPropertyName("midias")]
        public DashboardMedia Media { get; set; } = new();
    }

    public class DashboardCounts
    {
        [JsonPropertyName("cadastros")]
        public int Registries { get; set; }

        [JsonPropertyName("pessoas")]
        public int People { get; set; }

        [JsonPropertyName("veiculos")]
        public int Vehicles { get; set; }

        [JsonPropertyName("registros_memoria")]
        public int MemoryRecords { get; set; }
    }

    public class DashboardMedia
    {
        [JsonPropertyName("facial")]
        public int Facial { get; set; }

        [JsonPropertyName("rfid")]
        public int Rfid { get; set; }

        [JsonPropertyName("chaveiro_rfid")]
        public int RfidKeychain { get; set; }

        [JsonPropertyName("senha")]
        public int Password { get; set; }

        [JsonPropertyName("biometria")]
        public int Biometrics { get; set; }

        [JsonPropertyName("lpr")]
        public int Lpr { get; set; }

        [JsonPropertyName("tag_adesivo")]
        public int StickerTag { get; set; }

        [JsonPropertyName("tag_antimetal")]
        public int AntimetalTag { get; set; }

        [JsonPropertyName("cartao_rfid")]
        public int RfidCard { get; set; }

        [JsonPropertyName("controle_remoto")]
        public int RemoteControl { get; set; }
    }

    /// <summary>
    /// GET /device-info - Controller hardware information
    /// </summary>
    public class DeviceInfo
    {
        [JsonPropertyName("gid")]
        public int Gid { get; set; }

        [JsonPropertyName("gid_str")]
        public string GidStr { get; set; } = string.Empty;

        [JsonPropertyName("cliente_id")]
        public int ClientId { get; set; }

        [JsonPropertyName("hw_model")]
        public string HwModel { get; set; } = string.Empty;

        [JsonPropertyName("fw_version")]
        public string FwVersion { get; set; } = string.Empty;

        [JsonPropertyName("build_date")]
        public string BuildDate { get; set; } = string.Empty;

        [JsonPropertyName("datetime_utc")]
        public string DatetimeUtc { get; set; } = string.Empty;

        [JsonPropertyName("uptime_sec")]
        public int UptimeSec { get; set; }

        [JsonPropertyName("uptime_str")]
        public string UptimeStr { get; set; } = string.Empty;

        [JsonPropertyName("cpu_temp_c")]
        public double CpuTempC { get; set; }

        [JsonPropertyName("cpu_load_1")]
        public double CpuLoad1 { get; set; }

        [JsonPropertyName("cpu_load_5")]
        public double CpuLoad5 { get; set; }

        [JsonPropertyName("cpu_load_15")]
        public double CpuLoad15 { get; set; }

        [JsonPropertyName("procs_running")]
        public int ProcsRunning { get; set; }

        [JsonPropertyName("mem_total_kb")]
        public int MemTotalKb { get; set; }

        [JsonPropertyName("mem_free_kb")]
        public int MemFreeKb { get; set; }

        [JsonPropertyName("mem_avail_kb")]
        public int MemAvailKb { get; set; }

        [JsonPropertyName("mem_used_pct")]
        public int MemUsedPct { get; set; }
    }

    #endregion

    #region Webhook - GET/POST/DELETE /webhook

    /// <summary>
    /// Webhook configuration (up to 4 slots, id=1..4)
    /// The controller sends an HTTP POST to the configured URL when an event occurs.
    /// </summary>
    public class WebhookConfig
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("url")]
        public string Url { get; set; } = string.Empty;

        /// <summary>1 = notify registered access</summary>
        [JsonPropertyName("registered")]
        public int Registered { get; set; }

        /// <summary>1 = notify unregistered access</summary>
        [JsonPropertyName("unregistered")]
        public int Unregistered { get; set; }

        /// <summary>1 = notify sensor events</summary>
        [JsonPropertyName("sensors")]
        public int Sensors { get; set; }

        /// <summary>1 = notify logs</summary>
        [JsonPropertyName("logs")]
        public int Logs { get; set; }
    }

    /// <summary>
    /// Webhook listing response.
    /// </summary>
    public class WebhookListResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("items")]
        public List<WebhookConfig> Items { get; set; } = new();
    }

    #endregion

    #region Video Source - GET/POST/PUT/DELETE /video-source

    /// <summary>
    /// Video channel configuration for the controller.
    /// </summary>
    public class VideoSourceConfig
    {
        [JsonPropertyName("ret")]
        public int? Ret { get; set; }

        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("auto_detect")]
        public int AutoDetect { get; set; }

        [JsonPropertyName("channel_name")]
        public string ChannelName { get; set; } = string.Empty;

        [JsonPropertyName("ip")]
        public string Ip { get; set; } = string.Empty;

        [JsonPropertyName("username")]
        public string Username { get; set; } = string.Empty;

        [JsonPropertyName("password")]
        public string Password { get; set; } = string.Empty;

        [JsonPropertyName("rtsp_port")]
        public int RtspPort { get; set; } = 554;

        [JsonPropertyName("uri_hd")]
        public string UriHd { get; set; } = string.Empty;

        [JsonPropertyName("uri_sd")]
        public string UriSd { get; set; } = string.Empty;

        [JsonPropertyName("detected_uri_hd")]
        public string DetectedUriHd { get; set; } = string.Empty;

        [JsonPropertyName("detected_uri_sd")]
        public string DetectedUriSd { get; set; } = string.Empty;

        [JsonPropertyName("brand")]
        public string Brand { get; set; } = string.Empty;

        [JsonPropertyName("model")]
        public string Model { get; set; } = string.Empty;

        [JsonPropertyName("mac_address")]
        public string MacAddress { get; set; } = string.Empty;

        [JsonPropertyName("cloud_id")]
        public string CloudId { get; set; } = string.Empty;

        [JsonPropertyName("lpr_enabled")]
        public int LprEnabled { get; set; }

        [JsonPropertyName("face_enabled")]
        public int FaceEnabled { get; set; }

        [JsonPropertyName("car_enabled")]
        public int CarEnabled { get; set; }

        [JsonPropertyName("animal_enabled")]
        public int AnimalEnabled { get; set; }

        [JsonPropertyName("face_rec_enabled")]
        public int FaceRecEnabled { get; set; }

        [JsonPropertyName("lpr_threshold")]
        public int LprThreshold { get; set; } = 70;

        [JsonPropertyName("face_threshold")]
        public int FaceThreshold { get; set; } = 70;

        [JsonPropertyName("car_threshold")]
        public int CarThreshold { get; set; } = 70;

        [JsonPropertyName("animal_threshold")]
        public int AnimalThreshold { get; set; } = 70;

        [JsonPropertyName("face_rec_threshold")]
        public int FaceRecThreshold { get; set; } = 70;

        [JsonIgnore]
        public bool Active => !string.IsNullOrWhiteSpace(Ip);
    }

    /// <summary>
    /// Video channel listing response.
    /// </summary>
    public class VideoSourceListResponse
    {
        [JsonPropertyName("ret")]
        public int Ret { get; set; }

        [JsonPropertyName("max_channels")]
        public int MaxChannels { get; set; }

        [JsonPropertyName("items")]
        public List<VideoSourceConfig> Items { get; set; } = new();
    }

    #endregion
}
